### ISSUE TITLE
自定义规则无法使用http代理

### ISSUE THREAD

**Issue by Cappuccin0** [hellowingy/wingy-announcement#36]
确切的说，我只尝试了http代理，不确定ss或者socks代理是否也能正常工作。

ios 10.2.1, 试过wingy lite和pro的最新版本 v1.1.6

重现步骤：

1. 任选一个国内的http代理，确保其可用 （直接在『设置-wifi-http代理』中使用可正常访问网站，再取消确保直接连接）。我一般直接从cn-proxy.com上面随便选一个。
2. 使用文末的自定义配置，并激活配置。
3. 打开Safari测试网页，譬如ip138。

Expect：
第一步中可正常打开的网页（已经设置了系统全局代理），在第三步中也应正常打开

Actual：
激活wingy的vpn配置后所有网页均无法正常打开，除了规则中已设置使用direct的地址，譬如127.0.0.1/24和baidu.com，或非CN网站。

设置自定义规则的目的，主要是为了在墙外时可以通过国内代理翻回去访问有国内ip限制的网站。但由于测试时是在墙内（i.e. 国内主机通过国内代理访问国内网站），所以应该不涉及任何与墙有关的干扰。

自定义规则如下：
```
version: 2
adapter:
 - id: cnproxy
   type: http
   host: 111.7.174.147 # 代理地址可从cn-proxy.com获取
   port: 80
   secured: true #可选，是否为HTTPS代理，默认false
   auth: true #可选，是否需要身份验证
   username: proxy_username #可选
   password: proxy_password #可选
rule:
 - type: iplist
   criteria:
    - 127.0.0.0/8
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 224.0.0.0/8
    - 169.254.0.0/16
   adapter: direct
 - type: domainlist
   criteria:
    - s,baidu.com
    - s,asiainfo.com
    - s,163.com
    - s,youdao.com
    - s,jd.com
    - s,cmbchina.com
    - s,oschina.net
    - s,taobao.com
    - s,aliyun.com
    - s,alipay.com
    - s,tmall.com
    - s,yinxiang.com
    - s,qq.com
    - s,tencent.com
    - s,10086.cn
    - s,weixin.com
    - s,apple.com
    - s,cdn-apple.com
    - s,icloud.com
    - s,icloud-content.com
    - s,itunes.com
    - s,me.com
    - s,mzstatic.com
    - s,crashlytics.com
    - s,localhost
   adapter: direct
 - type: country
   country: CN
   match: true
   adapter: cnproxy
 - type: all
   adapter: direct
  ```
